### ISSUE TITLE
Cannot get transfer_to_main to work- Invalid Parameters

### ISSUE THREAD

**Issue by mcplums** [kmadac/bitstamp-python-client#32]
I am calling the transfer_to_main function with

` trading_client.transfer_to_main(0.05,"ltc")`

Yet I get the following error:

```
root@XXX:~# python test3.py
.Traceback (most recent call last):
  File "test3.py", line 34, in process_withdrawals
    trading_client.transfer_to_main(0.05,"ltc")
  File "/root/anaconda3/lib/python3.6/site-packages/bitstamp/bitstampclienttest.py", line 403, in transfer_to_main
    version=2)
  File "/root/anaconda3/lib/python3.6/site-packages/bitstamp/bitstampclienttest.py", line 48, in _post
    return self._request(requests.post, *args, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/bitstamp/bitstampclienttest.py", line 93, in _request
    raise BitstampError(json_response.get('reason'))
bitstamp.bitstampclienttest.BitstampError: Invalid parameters
```
What am I doing wrong?

Thanks!

**Comment by jorijnsmit** [comment]
Try `trading_client.transfer_to_main(amount='0.05', currency='ltc')`

**Comment by kmadac** [comment]
Closing issue as there is no update for more than a year.
